module.exports = {
	getCountryWithCCTLD : function (searchCode)
	{
		var list = [
		{"key" : "ac", "country" : "Île de l’Ascension"},
		{"key" : "ad", "country" : "Andorre"},
		{"key" : "ae", "country" : "Émirats arabes unis"},
		{"key" : "af", "country" : "Afghanistan"},
		{"key" : "ag", "country" : "Antigua-et-Barbuda"},
		{"key" : "ai", "country" : "Anguilla"},
		{"key" : "al", "country" : "Albanie"},
		{"key" : "dz", "country" : "Algérie"},
		{"key" : "am", "country" : "Arménie"},
		{"key" : "an", "country" : "Antilles néerlandaises"},
		{"key" : "ao", "country" : "Angola"},
		{"key" : "aq", "country" : "Antarctique"},
		{"key" : "ar", "country" : "Argentine"},
		{"key" : "as", "country" : "Samoa américaines"},
		{"key" : "at", "country" : "Autriche"},
		{"key" : "au", "country" : "Australie"},
		{"key" : "aw", "country" : "Aruba"},
		{"key" : "ax", "country" : "Åland"},
		{"key" : "az", "country" : "Azerbaïdjan"},
		{"key" : "ba", "country" : "Bosnie-Herzégovine"},
		{"key" : "bb", "country" : "Barbade"},
		{"key" : "bd", "country" : "Bangladesh"},
		{"key" : "be", "country" : "Belgique"},
		{"key" : "bf", "country" : "Burkina Faso"},
		{"key" : "bg", "country" : "Bulgarie"},
		{"key" : "bh", "country" : "Bahreïn"},
		{"key" : "bi", "country" : "Burundi"},
		{"key" : "bj", "country" : "Bénin"},
		{"key" : "bm", "country" : "Bermudes"},
		{"key" : "bn", "country" : "Brunei"},
		{"key" : "bo", "country" : "Bolivie"},
		{"key" : "br", "country" : "Brésil"},
		{"key" : "bs", "country" : "Bahamas"},
		{"key" : "bt", "country" : "Bhoutan"},
		{"key" : "bu", "country" : "Birmanie"},
		{"key" : "bv", "country" : "Île Bouvet"},
		{"key" : "bw", "country" : "Botswana"},
		{"key" : "by", "country" : "Biélorussie"},
		{"key" : "bz", "country" : "Belize"},
		{"key" : "ca", "country" : "Canada"},
		{"key" : "cc", "country" : "Îles Cocos"},
		{"key" : "cd", "country" : "République démocratique du Congo"},
		{"key" : "cf", "country" : "République centrafricaine"},
		{"key" : "cg", "country" : "Congo"},
		{"key" : "ch", "country" : "Suisse"},
		{"key" : "ci", "country" : "Côte d'Ivoire"},
		{"key" : "ck", "country" : "Îles Cook"},
		{"key" : "cl", "country" : "Chili"},
		{"key" : "cm", "country" : "Cameroun"},
		{"key" : "cn", "country" : "Chine"},
		{"key" : "co", "country" : "Colombie"},
		{"key" : "cr", "country" : "Costa Rica"},
		{"key" : "cs", "country" : "Serbie-et-Monténégro"},
		{"key" : "cu", "country" : "Cuba"},
		{"key" : "cv", "country" : "Cap-Vert"},
		{"key" : "cx", "country" : "Île Christmas"},
		{"key" : "cy", "country" : "Chypre"},
		{"key" : "cz", "country" : "République tchèque"},
		{"key" : "dd", "country" : "ex-RDA"},
		{"key" : "de", "country" : "Allemagne"},
		{"key" : "dj", "country" : "Djibouti"},
		{"key" : "dk", "country" : "Danemark"},
		{"key" : "dm", "country" : "Dominique"},
		{"key" : "do", "country" : "République dominicaine"},
		{"key" : "dz", "country" : "Algérie"},
		{"key" : "ec", "country" : "Équateur"},
		{"key" : "ee", "country" : "Estonie"},
		{"key" : "eg", "country" : "Égypte"},
		{"key" : "eh", "country" : "Sahara occidental"},
		{"key" : "er", "country" : "Érythrée"},
		{"key" : "es", "country" : "Espagne"},
		{"key" : "et", "country" : "Éthiopie"},
		{"key" : "eu", "country" : "Union européenne"},
		{"key" : "fi", "country" : "Finlande"},
		{"key" : "fj", "country" : "Fidji"},
		{"key" : "fk", "country" : "Îles Malouines"},
		{"key" : "fm", "country" : "Micronésie"},
		{"key" : "fo", "country" : "Îles Féroé"},
		{"key" : "fr", "country" : "France"},
		{"key" : "ga", "country" : "Gabon"},
		{"key" : "gb", "country" : "Grande-Bretagne"},
		{"key" : "gd", "country" : "Grenade"},
		{"key" : "ge", "country" : "Géorgie"},
		{"key" : "gf", "country" : "Guyane française"},
		{"key" : "gg", "country" : "Guernesey"},
		{"key" : "gh", "country" : "Ghana"},
		{"key" : "gi", "country" : "Gibraltar"},
		{"key" : "gl", "country" : "Groenland"},
		{"key" : "gm", "country" : "Gambie"},
		{"key" : "gn", "country" : "Guinée"},
		{"key" : "gp", "country" : "Guadeloupe"},
		{"key" : "gq", "country" : "Guinée équatoriale"},
		{"key" : "gr", "country" : "Grèce"},
		{"key" : "gs", "country" : "Géorgie du Sud-et-les Îles Sandwich du Sud"},
		{"key" : "gt", "country" : "Guatemala"},
		{"key" : "gu", "country" : "Guam"},
		{"key" : "gw", "country" : "Guinée-Bissau"},
		{"key" : "gy", "country" : "Guyana"},
		{"key" : "hk", "country" : "Hong Kong"},
		{"key" : "hm", "country" : "Îles Heard-et-MacDonald"},
		{"key" : "hn", "country" : "Honduras"},
		{"key" : "hr", "country" : "Croatie"},
		{"key" : "ht", "country" : "Haïti"},
		{"key" : "hu", "country" : "Hongrie"},
		{"key" : "id", "country" : "Indonésie"},
		{"key" : "ie", "country" : "Irlande"},
		{"key" : "il", "country" : "Israël"},
		{"key" : "im", "country" : "Île de Man"},
		{"key" : "in", "country" : "Inde"},
		{"key" : "io", "country" : "Territoire britannique de l'océan Indien"},
		{"key" : "iq", "country" : "Irak"},
		{"key" : "ir", "country" : "Iran"},
		{"key" : "is", "country" : "Islande"},
		{"key" : "it", "country" : "Italie"},
		{"key" : "je", "country" : "Jersey"},
		{"key" : "jm", "country" : "Jamaïque"},
		{"key" : "jo", "country" : "Jordanie"},
		{"key" : "jp", "country" : "Japon"},
		{"key" : "ke", "country" : "Kenya"},
		{"key" : "kg", "country" : "Kirghizstan"},
		{"key" : "kh", "country" : "Cambodge"},
		{"key" : "ki", "country" : "Kiribati"},
		{"key" : "km", "country" : "Comores"},
		{"key" : "kn", "country" : "Saint-Christophe-et-Niévès"},
		{"key" : "kp", "country" : "Corée du Nord"},
		{"key" : "kr", "country" : "Corée du Sud"},
		{"key" : "kw", "country" : "Koweït"},
		{"key" : "ky", "country" : "Îles Caïmans"},
		{"key" : "kz", "country" : "Kazakhstan"},
		{"key" : "la", "country" : "Laos"},
		{"key" : "lb", "country" : "Liban"},
		{"key" : "lc", "country" : "Sainte-Lucie"},
		{"key" : "li", "country" : "Liechtenstein"},
		{"key" : "lk", "country" : "Sri Lanka"},
		{"key" : "lr", "country" : "Libéria"},
		{"key" : "ls", "country" : "Lesotho"},
		{"key" : "lt", "country" : "Lituanie"},
		{"key" : "lu", "country" : "Luxembourg"},
		{"key" : "lv", "country" : "Lettonie"},
		{"key" : "ly", "country" : "Libye"},
		{"key" : "ma", "country" : "Maroc"},
		{"key" : "mc", "country" : "Monaco"},
		{"key" : "md", "country" : "Moldavie"},
		{"key" : "me", "country" : "Monténégro"},
		{"key" : "mg", "country" : "Madagascar"},
		{"key" : "mh", "country" : "Îles Marshall"},
		{"key" : "mk", "country" : "Macédoine"},
		{"key" : "ml", "country" : "Mali"},
		{"key" : "mm", "country" : "Birmanie"},
		{"key" : "mn", "country" : "Mongolie"},
		{"key" : "mo", "country" : "Macao"},
		{"key" : "mp", "country" : "Îles Mariannes du Nord"},
		{"key" : "mq", "country" : "Martinique"},
		{"key" : "mr", "country" : "Mauritanie"},
		{"key" : "ms", "country" : "Montserrat"},
		{"key" : "mt", "country" : "Malte"},
		{"key" : "mu", "country" : "Maurice"},
		{"key" : "mv", "country" : "Maldives"},
		{"key" : "mw", "country" : "Malawi"},
		{"key" : "mx", "country" : "Mexique"},
		{"key" : "my", "country" : "Malaisie"},
		{"key" : "mz", "country" : "Mozambique"},
		{"key" : "na", "country" : "Namibie"},
		{"key" : "nc", "country" : "Nouvelle-Calédonie"},
		{"key" : "ne", "country" : "Niger"},
		{"key" : "nf", "country" : "Île Norfolk"},
		{"key" : "ng", "country" : "Nigeria"},
		{"key" : "ni", "country" : "Nicaragua"},
		{"key" : "nl", "country" : "Pays-Bas"},
		{"key" : "no", "country" : "Norvège"},
		{"key" : "np", "country" : "Népal"},
		{"key" : "nr", "country" : "Nauru"},
		{"key" : "nu", "country" : "Niue"},
		{"key" : "nz", "country" : "Nouvelle-Zélande"},
		{"key" : "om", "country" : "Oman"},
		{"key" : "pa", "country" : "Panama"},
		{"key" : "pe", "country" : "Pérou"},
		{"key" : "pf", "country" : "Polynésie française"},
		{"key" : "pg", "country" : "Papouasie-Nouvelle-Guinée"},
		{"key" : "ph", "country" : "Philippines"},
		{"key" : "pk", "country" : "Pakistan"},
		{"key" : "pl", "country" : "Pologne"},
		{"key" : "pm", "country" : "Saint-Pierre-et-Miquelon"},
		{"key" : "pn", "country" : "Pitcairn"},
		{"key" : "pr", "country" : "Porto Rico"},
		{"key" : "ps", "country" : "Autorité palestinienne"},
		{"key" : "pt", "country" : "Portugal"},
		{"key" : "pw", "country" : "Palaos"},
		{"key" : "py", "country" : "Paraguay"},
		{"key" : "qa", "country" : "Qatar"},
		{"key" : "re", "country" : "La Réunion"},
		{"key" : "ro", "country" : "Roumanie"},
		{"key" : "rs", "country" : "Serbie"},
		{"key" : "ru", "country" : "Russie"},
		{"key" : "rw", "country" : "Rwanda"},
		{"key" : "sa", "country" : "Arabie saoudite"},
		{"key" : "sb", "country" : "Salomon"},
		{"key" : "sc", "country" : "Seychelles"},
		{"key" : "sd", "country" : "Soudan"},
		{"key" : "se", "country" : "Suède"},
		{"key" : "sg", "country" : "Singapour"},
		{"key" : "sh", "country" : "Sainte-Hélène"},
		{"key" : "si", "country" : "Slovénie"},
		{"key" : "sj", "country" : "Svalbard et Jan Mayen"},
		{"key" : "sk", "country" : "Slovaquie"},
		{"key" : "sl", "country" : "Sierra Leone"},
		{"key" : "sm", "country" : "Saint-Marin"},
		{"key" : "sn", "country" : "Sénégal"},
		{"key" : "so", "country" : "Somalie"},
		{"key" : "sr", "country" : "Suriname"},
		{"key" : "ss", "country" : "Soudan du Sud"},
		{"key" : "st", "country" : "Sao Tomé-et-Principe"},
		{"key" : "su", "country" : "Union soviétique"},
		{"key" : "sv", "country" : "Salvador"},
		{"key" : "sx", "country" : "Saint-Martin"},
		{"key" : "sy", "country" : "Syrie"},
		{"key" : "sz", "country" : "Swaziland"},
		{"key" : "tc", "country" : "Îles Turques et Caïques"},
		{"key" : "td", "country" : "Tchad"},
		{"key" : "tf", "country" : "Terres australes et antarctiques françaises"},
		{"key" : "tg", "country" : "Togo"},
		{"key" : "th", "country" : "Thaïlande"},
		{"key" : "tj", "country" : "Tadjikistan"},
		{"key" : "tk", "country" : "Tokelau"},
		{"key" : "tl", "country" : "Timor oriental"},
		{"key" : "tm", "country" : "Turkménistan"},
		{"key" : "tn", "country" : "Tunisie"},
		{"key" : "to", "country" : "Tonga"},
		{"key" : "tp", "country" : "Timor oriental"},
		{"key" : "tr", "country" : "Turquie"},
		{"key" : "tt", "country" : "Trinité-et-Tobago"},
		{"key" : "tv", "country" : "Tuvalu"},
		{"key" : "tw", "country" : "Taïwan"},
		{"key" : "tz", "country" : "Tanzanie"},
		{"key" : "ua", "country" : "Ukraine"},
		{"key" : "ug", "country" : "Ouganda"},
		{"key" : "uk", "country" : "Royaume-Uni"},
		{"key" : "um", "country" : "Îles mineures éloignées des États-Unis"},
		{"key" : "us", "country" : "États-Unis"},
		{"key" : "uy", "country" : "Uruguay"},
		{"key" : "uz", "country" : "Ouzbékistan"},
		{"key" : "va", "country" : "Vatican"},
		{"key" : "vc", "country" : "Saint-Vincent-et-les Grenadines"},
		{"key" : "ve", "country" : "Venezuela"},
		{"key" : "vg", "country" : "Îles Vierges britanniques"},
		{"key" : "vi", "country" : "Îles Vierges américaines"},
		{"key" : "vn", "country" : "Viêt Nam"},
		{"key" : "vu", "country" : "Vanuatu"},
		{"key" : "wf", "country" : "Wallis-et-Futuna"},
		{"key" : "ws", "country" : "Samoa"},
		{"key" : "ye", "country" : "Yémen"},
		{"key" : "yt", "country" : "Mayotte"},
		{"key" : "yu", "country" : "Yougoslavie"},
		{"key" : "za", "country" : "Afrique du Sud"},
		{"key" : "zm", "country" : "Zambie"},
		{"key" : "zr", "country" : "Zaïre"},
		{"key" : "zw", "country" : "Zimbabwe"}
		];

		var value = searchCode;

		for (var i = 0; i < list.length; i++)
		{
			var object = list[i];
			if (object.key == searchCode)
			{
				value = object.country;
				break;
			}
		}
		
		return value;
	}
}